### ISSUE TITLE
Assertion is raised for a simple nc copy

### ISSUE THREAD

**Issue by minomicetto** [ESiWACE/esdm-netcdf#1]
Current version of the library with current version of esdm returns the following error

`/path/to/esdm/deps/smd/src/smd-core.c:2494: smd_attr_link: Assertion 'child->parent == ((void *)0)' failed.`

when typing the following command

`nccopy tos_O1_2001-2002.nc esdm://tos`

where the example file is https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc.

**Comment by JulianKunkel** [comment]
Thanks for the bug report.
I verified with the current code (with and without debug flags).
I reckon what has happened is that you have accidentally an older SMD
(remote repo) code.

To verify
$ cd deps/smd
$ git log
Should show a commit "6ac4921ef5" from June 3rd

$ git submodule update --remote --recursive
Should update it.

My test worked as follows:
$ wget
https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc
$ mkfs.esdm -g -l --create  --remove --ignore-errors
$ nccopy tos_O1_2001-2002.nc esdm://tos
$ ncdump -h esdm://tos
$ nccopy esdm://tos out.nc

esdm.conf:
{"esdm":
{
"backends": [
{"type": "POSIX", "id": "tmp", "target": "./_esdm",
"performance-model" : {"latency" : 0.000001, "throughput" : 500.0},
"max-threads-per-node" : 4,
"max-fragment-size" : 104857600,
"max-global-threads" : 8,
"accessibility" : "global"
}
],
"metadata": {"type": "metadummy",
"id": "md",
"target": "./_metadummy",
  "accessibility" : "global"}
}
}

Thanks for letting me know such that the bug can be resolved.

**Comment by minomicetto** [comment]
Thanks Julian.
I am using the correct version of SMD.
More in detail, I am experiencing  a problem with the creation of the global attribute "title", namely an array of 73 chars (I believe the first attribute processed by the ESDM library).
While the function smd_attr_copy_val_to_internal() of https://github.com/JulianKunkel/smd/blob/master/src/smd-core.c performs a copy of this attribute char-by-char, the value of child->parent (where the assertion is raised) switches from NULL to a non-NULL value.
In the case-section of smd_attr_copy_val_to_internal() associated with the type SMD_TYPE_ARRAY (namely the type of the target attribute) I believe the line https://github.com/JulianKunkel/smd/blob/master/src/smd-core.c#L1327 is useless, but it does not impact on the execution (except for an useless repetition of the copy), so my problem is due to another cause.

**Comment by JulianKunkel** [comment]
Thanks Cosimo,
I have now updated the Docker build instructions for Ubuntu20.04, creating
the dev/docker/ubuntu-whole-stack
description which builds NetCDF as well and runs this particular test.
I wanted to ensure to have a clean environment.
In this directory, I run
$ ./create-container.sh
$ ./run-container.sh
$ ./basic-test.sh
The latter is the scripted version of your test.
I run with --debug and without for ESDM, in all cases it worked.

At the moment, I suspect that it might be a compiler issue as the casting
is a bit fragile, if I know which distribution + version you have, I will
create a docker to mimic it and test.
If you have docker, could you try if the docker image works for you (just
for verification)?

Thanks.

**Comment by minomicetto** [comment]
Thanks Julian.
I am going to set up the Docker container and to reply you as soon as possible.
I agree that it might be a compiler issue: my OS is CentOS 7, just updated with the kernel: 3.10.0-1160.6.1.el7.x86_64 #1 SMP. I am using the gcc 4.9.4, as the default version od the distro (4.8) cannot support stdatomic.
Maybe, I could simply update my gcc to check the behaviour.

**Comment by JulianKunkel** [comment]
Great, I will check this out.
I realized that there are issues with GCC < 4.9.
I'll be testing now the route here:
https://ahelpme.com/linux/centos7/how-to-install-gnu-gcc-8-on-centos-7/

**Comment by JulianKunkel** [comment]
It was a good exercise:
I have sketched the whole stack installation in
dev/docker/centos7-whole-stack and could run the test also
successfully as follows:
$ cd dev/docker/centos7-whole-stack
$ ./create-container.sh
$ ./run-container.sh
# Now inside the container:
$ ./basic-test.sh

I reckon, it was some kind of gcc-4.8 interference.
The same steps using gcc8 should work for you outside of the container.
